spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: false
  datasource: #
    url: jdbc:mysql://db-oeatp-kr.vpc-pub-cdb.ntruss.com:3306/kcubeon_appr_trns?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kcubeon_appr
    password: kcubeon0302!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 180000
      keepalive-time: 300000
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.StatementCreatorUtils: INFO
    org.springframework.batch.core: INFO
    org.springframework.transaction: INFO
migration:
  tenant-id : 4187 # 개발계 tenantid
  default-userid : 25093 # 퇴사자 USERID
  default-kmid : 22718 # 디폴트 부서 KMID
  asis-min-documentid: 17   # select min(documentid) from dp_app_doc WHERE WRITETIMEYMD <'20250101';
  asis-max-documentid: 1510526 # select max(documentid) from dp_app_doc WHERE WRITETIMEYMD <'20250101';
  form-id-A: 16 # 이관용 양식ID
  form-id-B: 17 # 이관용 양식ID 회계전표
  ctgrId : 2 # 부서문서함 category id
  tobe-min-itemid: 0 # select min(itemid) from ap_item ; -- 해당 이관범위조건 추가
  tobe-max-itemid: 1200000 # select max(itemid) from ap_item ; -- 해당 이관범위조건 추가
